### ISSUE TITLE
Does not support Italic Text

### ISSUE THREAD

**Issue by samcv** [tadzik/Terminal-ANSIColor#11]
Code 3 is Italic on, Code 23 is Italic off.

Supported in terminals with TTF/OTF fonts (seems to work for me on multiple terminals as long as I'm not using bitmap fonts (plus i don't think any of my bitmap fonts have italic style anyway)

Ctrl + F for the word Italic here: https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_codes

**Comment by tadzik** [comment]
Fixed now, thanks!
